# Import packages

In [1]:
import pandas as pd
import numpy as np
from scipy.stats import norm
from scipy import stats
from scipy.stats import boxcox
import seaborn as sns
from scipy.stats import ttest_ind

# Loading Datasets

In [2]:
tv_kids = pd.read_csv("kids.csv")
pd.options.display.max_rows = 10000
pd.options.display.max_columns = 10000
tv_kids.head(1)

show_id               title  StreamR listed_in date_added  release_year  \
0  70234439  Transformers Prime  TV_Show  Kids' TV   9/8/2018          2013   

         country   Kids_TV  British  Cult  Crime  Docuseries  International  \
0  United States  Kids' TV        0     0      0           0              0   

   Kids  Reality  Romantic  Spanish  Stand_Up_Comedy  Action  Comedies  \
0     1        0         0        0                0       0         0   

   Dramas  Horror  Sci_Fi  TV_Shows  
0       0       0       0         0

In [3]:
tv_kids1 = tv_kids.drop(['title', 'listed_in', 'StreamR', 'date_added', 'country'], axis=1)
tv_kids1.dropna()
tv_kids1.head(1)  

show_id  release_year   Kids_TV  British  Cult  Crime  Docuseries  \
0  70234439          2013  Kids' TV        0     0      0           0   

   International  Kids  Reality  Romantic  Spanish  Stand_Up_Comedy  Action  \
0              0     1        0         0        0                0       0   

   Comedies  Dramas  Horror  Sci_Fi  TV_Shows  
0         0       0       0       0         0

In [6]:
tv_crime = pd.read_csv("crime.csv")
pd.options.display.max_rows = 10000
pd.options.display.max_columns = 10000
tv_crime.head(1)

show_id               title  StreamR listed_in date_added  release_year  \
0  70234439  Transformers Prime  TV_Show  Kids' TV   9/8/2018          2013   

         country Crime   Crime_TV   Docuseries   International   Kids  Korean  \
0  United States   NaN          0            0               0      0       0   

    Reality   Romantic   Science  Spanish   Stand_Up_Comedy  Action  Comedies  \
0         0          0         0        0                 0       0         0   

   Dramas  Horror  Mysteries  Sci_Fi  Thrillers  TV_Shows  
0       0       0          0       0          0         0

In [7]:
tv_crime1 = tv_crime.drop(['title', 'listed_in', 'StreamR', 'date_added', 'country'], axis=1)
tv_crime2 = tv_crime1.dropna()
tv_crime2.head(1)

show_id  release_year                    Crime   Crime_TV   Docuseries  \
2  80163890          2016   International TV Shows          0            0   

    International   Kids  Korean   Reality   Romantic   Science  Spanish  \
2               1      0       0         0          0         0        0   

    Stand_Up_Comedy  Action  Comedies  Dramas  Horror  Mysteries  Sci_Fi  \
2                 0       0         0       0       0          0       0   

   Thrillers  TV_Shows  
2          0         0

In [8]:
tv_doc = pd.read_csv("doc.csv")
pd.options.display.max_rows = 10000
pd.options.display.max_columns = 10000
tv_doc.head(1)

show_id               title  StreamR listed_in date_added  release_year  \
0  70234439  Transformers Prime  TV_Show  Kids' TV   9/8/2018          2013   

         country Docuseries   International  Korean   Reality   Romantic  \
0  United States        NaN               0       0         0          0   

    Science  Spanish   Stand_Up_Comedy  Action  Comedies  Dramas  Horror  \
0         0        0                 0       0         0       0       0   

   Mysteries  Sci_Fi  Thrillers  TV_Shows  
0          0       0          0         0

In [10]:
tv_doc1 = tv_doc.drop(['title', 'listed_in', 'StreamR', 'date_added', 'country'], axis=1)
tv_doc2 = tv_doc1.dropna()
tv_doc2.head(1)

show_id  release_year                  Docuseries   International  Korean  \
2  80163890          2016   Spanish-Language TV Shows               0       0   

    Reality   Romantic   Science  Spanish   Stand_Up_Comedy  Action  Comedies  \
2         0          0         0        1                 0       0         0   

   Dramas  Horror  Mysteries  Sci_Fi  Thrillers  TV_Shows  
2       0       0          0       0          0         0

# Independent Chi Square Test Assumption Analysis

In [11]:
# Contingency Table
british_crosstab = pd.crosstab(tv_kids1['release_year'], tv_kids1['British'])
british_crosstab

British         0   1
release_year         
1925            1   0
1946            1   0
1963            1   0
1967            1   0
1968            1   0
1972            1   0
1974            0   1
1977            0   1
1979            1   0
1981            1   0
1985            1   0
1986            2   0
1988            2   0
1989            1   0
1990            3   0
1991            1   0
1992            1   1
1993            3   0
1994            1   0
1995            2   0
1996            3   0
1997            4   0
1998            3   0
1999            3   1
2000            3   0
2001            2   2
2002            3   0
2003            8   0
2004            8   1
2005           10   2
2006            6   3
2007           11   0
2008           18   2
2009           28   6
2010           37   1
2011           28   8
2012           50   8
2013           49  11
2014           68   7
2015          132  22
2016          208  29
2017          241  36
2018          378  39
2019          415  28
2020           18   1

In [12]:
# Running Independent Chi-Square
stats.chi2_contingency(british_crosstab)

(67.9441628931963,
 0.0117483781515714,
 44,
 array([[8.93346877e-01, 1.06653123e-01],
        [8.93346877e-01, 1.06653123e-01],
        [8.93346877e-01, 1.06653123e-01],
        [8.93346877e-01, 1.06653123e-01],
        [8.93346877e-01, 1.06653123e-01],
        [8.93346877e-01, 1.06653123e-01],
        [8.93346877e-01, 1.06653123e-01],
        [8.93346877e-01, 1.06653123e-01],
        [8.93346877e-01, 1.06653123e-01],
        [8.93346877e-01, 1.06653123e-01],
        [8.93346877e-01, 1.06653123e-01],
        [1.78669375e+00, 2.13306247e-01],
        [1.78669375e+00, 2.13306247e-01],
        [8.93346877e-01, 1.06653123e-01],
        [2.68004063e+00, 3.19959370e-01],
        [8.93346877e-01, 1.06653123e-01],
        [1.78669375e+00, 2.13306247e-01],
        [2.68004063e+00, 3.19959370e-01],
        [8.93346877e-01, 1.06653123e-01],
        [1.78669375e+00, 2.13306247e-01],
        [2.68004063e+00, 3.19959370e-01],
        [3.57338751e+00, 4.26612494e-01],
        [2.68004063e+00, 3.1995

British Genre: Looking at this, it looks like there is significant relationship between release year and British genre. 

In [13]:
# Spanish Contingency Table 
spanish_crosstab = pd.crosstab(tv_kids1['release_year'], tv_kids1['Spanish'])
spanish_crosstab

Spanish         0  1
release_year        
1925            1  0
1946            1  0
1963            1  0
1967            1  0
1968            1  0
1972            1  0
1974            1  0
1977            1  0
1979            1  0
1981            1  0
1985            1  0
1986            2  0
1988            2  0
1989            1  0
1990            3  0
1991            1  0
1992            2  0
1993            3  0
1994            1  0
1995            2  0
1996            3  0
1997            4  0
1998            3  0
1999            4  0
2000            3  0
2001            4  0
2002            3  0
2003            8  0
2004            9  0
2005           12  0
2006            9  0
2007           11  0
2008           20  0
2009           34  0
2010           38  0
2011           36  0
2012           58  0
2013           60  0
2014           75  0
2015          154  0
2016          236  1
2017          277  0
2018          417  0
2019          443  0
2020           19  0

In [14]:
# Running Independent Chi-Square
stats.chi2_contingency(spanish_crosstab)

(7.311730300847311,
 0.999999999933649,
 44,
 array([[9.99492128e-01, 5.07872016e-04],
        [9.99492128e-01, 5.07872016e-04],
        [9.99492128e-01, 5.07872016e-04],
        [9.99492128e-01, 5.07872016e-04],
        [9.99492128e-01, 5.07872016e-04],
        [9.99492128e-01, 5.07872016e-04],
        [9.99492128e-01, 5.07872016e-04],
        [9.99492128e-01, 5.07872016e-04],
        [9.99492128e-01, 5.07872016e-04],
        [9.99492128e-01, 5.07872016e-04],
        [9.99492128e-01, 5.07872016e-04],
        [1.99898426e+00, 1.01574403e-03],
        [1.99898426e+00, 1.01574403e-03],
        [9.99492128e-01, 5.07872016e-04],
        [2.99847638e+00, 1.52361605e-03],
        [9.99492128e-01, 5.07872016e-04],
        [1.99898426e+00, 1.01574403e-03],
        [2.99847638e+00, 1.52361605e-03],
        [9.99492128e-01, 5.07872016e-04],
        [1.99898426e+00, 1.01574403e-03],
        [2.99847638e+00, 1.52361605e-03],
        [3.99796851e+00, 2.03148807e-03],
        [2.99847638e+00, 1.5236

Spanish Genre: Looking at this, it looks like there is not significant relationship between release year and Spanish genre. 

# tv_crime2 Dataset

In [15]:
# Korean Contingency Table 
ckorean_crosstab = pd.crosstab(tv_crime2['release_year'], tv_crime2['Korean'])
ckorean_crosstab

Korean          0   1
release_year         
1963            1   0
1967            1   0
1968            1   0
1972            1   0
1974            1   0
1977            1   0
1979            1   0
1981            1   0
1988            1   0
1990            2   0
1992            2   0
1993            1   0
1995            1   0
1997            2   0
1998            2   0
1999            3   0
2000            2   0
2001            3   0
2002            2   0
2003            7   0
2004            8   0
2005            9   0
2006            8   0
2007            5   0
2008           19   0
2009           30   3
2010           29   1
2011           32   1
2012           39  10
2013           46   5
2014           55   6
2015          125  14
2016          168  22
2017          201  21
2018          318  14
2019          331  19
2020           16   0

In [16]:
# Running Independent Chi-Square
stats.chi2_contingency(ckorean_crosstab)

(37.95712802265382,
 0.3802137155115718,
 36,
 array([[9.27089881e-01, 7.29101194e-02],
        [9.27089881e-01, 7.29101194e-02],
        [9.27089881e-01, 7.29101194e-02],
        [9.27089881e-01, 7.29101194e-02],
        [9.27089881e-01, 7.29101194e-02],
        [9.27089881e-01, 7.29101194e-02],
        [9.27089881e-01, 7.29101194e-02],
        [9.27089881e-01, 7.29101194e-02],
        [9.27089881e-01, 7.29101194e-02],
        [1.85417976e+00, 1.45820239e-01],
        [1.85417976e+00, 1.45820239e-01],
        [9.27089881e-01, 7.29101194e-02],
        [9.27089881e-01, 7.29101194e-02],
        [1.85417976e+00, 1.45820239e-01],
        [1.85417976e+00, 1.45820239e-01],
        [2.78126964e+00, 2.18730358e-01],
        [1.85417976e+00, 1.45820239e-01],
        [2.78126964e+00, 2.18730358e-01],
        [1.85417976e+00, 1.45820239e-01],
        [6.48962916e+00, 5.10370836e-01],
        [7.41671904e+00, 5.83280955e-01],
        [8.34380893e+00, 6.56191075e-01],
        [7.41671904e+00, 5.832

Korean Genre: Looking at this, it looks like there is not significant relationship between release year and Korean genre. 

In [17]:
# Spanish Contingency Table 
ckorean_crosstab = pd.crosstab(tv_crime2['release_year'], tv_crime2['Spanish'])
ckorean_crosstab

Spanish         0   1
release_year         
1963            1   0
1967            1   0
1968            1   0
1972            1   0
1974            1   0
1977            1   0
1979            1   0
1981            1   0
1988            1   0
1990            2   0
1992            2   0
1993            1   0
1995            1   0
1997            2   0
1998            2   0
1999            3   0
2000            2   0
2001            3   0
2002            2   0
2003            7   0
2004            8   0
2005            9   0
2006            7   1
2007            5   0
2008           18   1
2009           33   0
2010           29   1
2011           33   0
2012           48   1
2013           50   1
2014           61   0
2015          135   4
2016          183   7
2017          216   6
2018          319  13
2019          342   8
2020           15   1

In [30]:
# Running Independent Chi-Square
stats.chi2_contingency(ckorean_crosstab)

(12.037391256199122,
 0.9999408393499934,
 36,
 array([[9.72344437e-01, 2.76555625e-02],
        [9.72344437e-01, 2.76555625e-02],
        [9.72344437e-01, 2.76555625e-02],
        [9.72344437e-01, 2.76555625e-02],
        [9.72344437e-01, 2.76555625e-02],
        [9.72344437e-01, 2.76555625e-02],
        [9.72344437e-01, 2.76555625e-02],
        [9.72344437e-01, 2.76555625e-02],
        [9.72344437e-01, 2.76555625e-02],
        [1.94468887e+00, 5.53111251e-02],
        [1.94468887e+00, 5.53111251e-02],
        [9.72344437e-01, 2.76555625e-02],
        [9.72344437e-01, 2.76555625e-02],
        [1.94468887e+00, 5.53111251e-02],
        [1.94468887e+00, 5.53111251e-02],
        [2.91703331e+00, 8.29666876e-02],
        [1.94468887e+00, 5.53111251e-02],
        [2.91703331e+00, 8.29666876e-02],
        [1.94468887e+00, 5.53111251e-02],
        [6.80641106e+00, 1.93588938e-01],
        [7.77875550e+00, 2.21244500e-01],
        [8.75109994e+00, 2.48900063e-01],
        [7.77875550e+00, 2.21

Spanish Genre: Looking at this, it looks like there is not significant relationship between release year and Spanish genre. 

# tv_doc2 Dataset

In [18]:
# Korean Contingency Table 
dkorean_crosstab = pd.crosstab(tv_doc2['release_year'], tv_crime2['Korean'])
dkorean_crosstab

Korean          0   1
release_year         
1968            1   0
1974            1   0
1977            1   0
1979            1   0
1990            2   0
1992            1   0
2001            1   0
2002            2   0
2003            2   0
2004            5   0
2005            4   0
2006            6   0
2007            2   0
2008           11   0
2009           13   3
2010           14   1
2011           19   1
2012           19  10
2013           31   4
2014           37   5
2015           84  12
2016          115  18
2017          117  17
2018          196   9
2019          209  18
2020            9   0

In [19]:
# Running Independent Chi-Square
stats.chi2_contingency(dkorean_crosstab)

(39.637309601871124,
 0.03176462073521469,
 25,
 array([[9.02097902e-01, 9.79020979e-02],
        [9.02097902e-01, 9.79020979e-02],
        [9.02097902e-01, 9.79020979e-02],
        [9.02097902e-01, 9.79020979e-02],
        [1.80419580e+00, 1.95804196e-01],
        [9.02097902e-01, 9.79020979e-02],
        [9.02097902e-01, 9.79020979e-02],
        [1.80419580e+00, 1.95804196e-01],
        [1.80419580e+00, 1.95804196e-01],
        [4.51048951e+00, 4.89510490e-01],
        [3.60839161e+00, 3.91608392e-01],
        [5.41258741e+00, 5.87412587e-01],
        [1.80419580e+00, 1.95804196e-01],
        [9.92307692e+00, 1.07692308e+00],
        [1.44335664e+01, 1.56643357e+00],
        [1.35314685e+01, 1.46853147e+00],
        [1.80419580e+01, 1.95804196e+00],
        [2.61608392e+01, 2.83916084e+00],
        [3.15734266e+01, 3.42657343e+00],
        [3.78881119e+01, 4.11188811e+00],
        [8.66013986e+01, 9.39860140e+00],
        [1.19979021e+02, 1.30209790e+01],
        [1.20881119e+02, 1.3

Korean Genre: Looking at this, it looks like there is significant relationship between release year and Korean genre. 

In [36]:
# Korean Contingency Table 
dkorean_crosstab = pd.crosstab(tv_doc2['release_year'], tv_crime2['Spanish'])
dkorean_crosstab

Spanish         0   1
release_year         
1968            1   0
1974            1   0
1977            1   0
1979            1   0
1990            2   0
1992            1   0
2001            1   0
2002            2   0
2003            2   0
2004            5   0
2005            4   0
2006            5   1
2007            2   0
2008           10   1
2009           16   0
2010           14   1
2011           20   0
2012           28   1
2013           34   1
2014           42   0
2015           93   3
2016          126   7
2017          130   4
2018          193  12
2019          219   8
2020            9   0

In [20]:
# Running Independent Chi-Square
stats.chi2_contingency(dkorean_crosstab)

(39.637309601871124,
 0.03176462073521469,
 25,
 array([[9.02097902e-01, 9.79020979e-02],
        [9.02097902e-01, 9.79020979e-02],
        [9.02097902e-01, 9.79020979e-02],
        [9.02097902e-01, 9.79020979e-02],
        [1.80419580e+00, 1.95804196e-01],
        [9.02097902e-01, 9.79020979e-02],
        [9.02097902e-01, 9.79020979e-02],
        [1.80419580e+00, 1.95804196e-01],
        [1.80419580e+00, 1.95804196e-01],
        [4.51048951e+00, 4.89510490e-01],
        [3.60839161e+00, 3.91608392e-01],
        [5.41258741e+00, 5.87412587e-01],
        [1.80419580e+00, 1.95804196e-01],
        [9.92307692e+00, 1.07692308e+00],
        [1.44335664e+01, 1.56643357e+00],
        [1.35314685e+01, 1.46853147e+00],
        [1.80419580e+01, 1.95804196e+00],
        [2.61608392e+01, 2.83916084e+00],
        [3.15734266e+01, 3.42657343e+00],
        [3.78881119e+01, 4.11188811e+00],
        [8.66013986e+01, 9.39860140e+00],
        [1.19979021e+02, 1.30209790e+01],
        [1.20881119e+02, 1.3

Spanish Genre: Looking at this, it looks like there is not significant relationship between release year and Spanish genre. 